import { createSlice, type PayloadAction } from "@reduxjs/toolkit"

export interface KPI {
  id: string
  name: string
  description: string
  type: "Percentage" | "Metric" | "Count"
  category: string
  targetValue: number
  currentValue: number
  unit: string
  isActive: boolean
  departmentId?: string
  departmentName?: string
  targetOperator: ">=" | "<=" | "=" | ">" | "<"
  dataSourceModule?: string
  dataSourceField?: string
  trackingFrequency?: "Daily" | "Weekly" | "Monthly" | "Quarterly"
  accountNumber?: string
  accountType?: string
  journalEntryType?: string
  createdAt: string
  updatedAt: string
}

export interface Goal {
  id: string
  title: string
  description: string
  type: "company" | "department" | "individual"
  category: string
  targetValue: number
  currentValue: number
  targetUnit: string
  progressPercentage: number
  status: "active" | "completed" | "cancelled" | "overdue"
  stage: "planning" | "execution" | "review" | "completed"
  priority: "low" | "medium" | "high"
  startDate: string
  endDate: string
  departmentId?: string
  departmentName?: string
  assignedUserId?: string
  assignedUserName?: string
  parentGoalId?: string
  targetOperator: ">=" | "<=" | "=" | ">" | "<"
  dataSourceModule?: string
  dataSourceField?: string
  trackingFrequency?: "Daily" | "Weekly" | "Monthly" | "Quarterly"
  nextCheckDate?: string
  createdAt: string
  updatedAt: string
}

export interface Task {
  id: string
  title: string
  description: string
  assignedUserId: string
  assignedUserName: string
  goalId?: string
  isPerformanceTask: boolean
  status: "pending" | "in_progress" | "completed" | "cancelled"
  priority: "low" | "medium" | "high"
  progress: number
  dueDate: string
  completedAt?: string
  createdAt: string
  updatedAt: string
}

export interface Department {
  id: string
  name: string
  description: string
  branch: string
  isActive: boolean
  _count?: {
    users: number
    goals: number
  }
  createdAt: string
  updatedAt: string
}

export interface DepartmentScorecard {
  departmentId: string
  departmentName: string
  totalGoals: number
  completedGoals: number
  inProgressGoals: number
  overdueGoals: number
  averageProgress: number
  performanceRating: "Excellent" | "Good" | "Fair" | "Poor"
  goals: Goal[]
  teamMembers: {
    userId: string
    name: string
    totalTasks: number
    completedTasks: number
    inProgressTasks: number
    performanceRating: string
  }[]
}

export interface UserScorecard {
  userId: string
  userName: string
  department: string
  totalGoals: number
  completedGoals: number
  inProgressGoals: number
  overdueGoals: number
  averageProgress: number
  performanceRating: "Excellent" | "Good" | "Fair" | "Poor"
  goals: Goal[]
  tasks: Task[]
}

interface PerformanceState {
  kpis: KPI[]
  goals: Goal[]
  tasks: Task[]
  departments: Department[]
  departmentScorecards: DepartmentScorecard[]
  userScorecards: UserScorecard[]
  loading: boolean
  crudLoading: boolean
  error: string | null
  selectedKPIType: string
  selectedKPICategory: string
  selectedKPIDepartment: string
  selectedKPIStatus: string
  kpiSearchTerm: string
  metrics: {
    totalKPIs: number
    activeKPIs: number
    completedGoals: number
    totalGoals: number
    completedTasks: number
    totalTasks: number
  }
}

const initialState: PerformanceState = {
  kpis: [
    // Financial KPIs
    {
      id: "kpi_001",
      name: "AUM Growth Rate",
      description: "Track Assets Under Management growth",
      type: "Metric",
      category: "financial",
      targetValue: 5000000,
      currentValue: 2500000,
      unit: "USD",
      isActive: true,
      departmentId: "dept_001",
      departmentName: "Finance",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "BalanceSheet.TotalAssets",
      trackingFrequency: "Monthly",
      accountNumber: "1000",
      accountType: "Asset",
      journalEntryType: "Debit",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_002",
      name: "Revenue Growth",
      description: "Year-over-year revenue growth percentage",
      type: "Percentage",
      category: "financial",
      targetValue: 25,
      currentValue: 18,
      unit: "%",
      isActive: true,
      departmentId: "dept_001",
      departmentName: "Finance",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "IncomeStatement.Revenue",
      trackingFrequency: "Quarterly",
      accountNumber: "4000",
      accountType: "Revenue",
      journalEntryType: "Credit",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_003",
      name: "Operating Margin",
      description: "Operating profit as percentage of revenue",
      type: "Percentage",
      category: "financial",
      targetValue: 30,
      currentValue: 28,
      unit: "%",
      isActive: true,
      departmentId: "dept_001",
      departmentName: "Finance",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "IncomeStatement.OperatingMargin",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Sales KPIs
    {
      id: "kpi_004",
      name: "Client Acquisition Rate",
      description: "Number of new clients acquired",
      type: "Count",
      category: "sales",
      targetValue: 50,
      currentValue: 32,
      unit: "clients",
      isActive: true,
      departmentId: "dept_002",
      departmentName: "Sales",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "ClientAcquisitionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_005",
      name: "Sales Conversion Rate",
      description: "Percentage of leads converted to clients",
      type: "Percentage",
      category: "sales",
      targetValue: 35,
      currentValue: 28,
      unit: "%",
      isActive: true,
      departmentId: "dept_002",
      departmentName: "Sales",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "ConversionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_006",
      name: "Average Deal Size",
      description: "Average value of closed deals",
      type: "Metric",
      category: "sales",
      targetValue: 100000,
      currentValue: 85000,
      unit: "USD",
      isActive: true,
      departmentId: "dept_002",
      departmentName: "Sales",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "AverageDealSize",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Operations KPIs
    {
      id: "kpi_007",
      name: "Task Completion Rate",
      description: "Percentage of tasks completed on time",
      type: "Percentage",
      category: "operations",
      targetValue: 90,
      currentValue: 85,
      unit: "%",
      isActive: true,
      departmentId: "dept_003",
      departmentName: "Operations",
      targetOperator: ">=",
      dataSourceModule: "TaskManagement",
      dataSourceField: "TaskCompletionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_008",
      name: "Process Efficiency Score",
      description: "Overall operational efficiency rating",
      type: "Percentage",
      category: "operations",
      targetValue: 85,
      currentValue: 78,
      unit: "%",
      isActive: true,
      departmentId: "dept_003",
      departmentName: "Operations",
      targetOperator: ">=",
      dataSourceModule: "Operations",
      dataSourceField: "EfficiencyScore",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // HR KPIs
    {
      id: "kpi_009",
      name: "Employee Satisfaction Score",
      description: "Average employee satisfaction rating",
      type: "Percentage",
      category: "hr",
      targetValue: 85,
      currentValue: 82,
      unit: "%",
      isActive: true,
      departmentId: "dept_004",
      departmentName: "Human Resources",
      targetOperator: ">=",
      dataSourceModule: "HR",
      dataSourceField: "SatisfactionScore",
      trackingFrequency: "Quarterly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_010",
      name: "Employee Retention Rate",
      description: "Percentage of employees retained",
      type: "Percentage",
      category: "hr",
      targetValue: 95,
      currentValue: 92,
      unit: "%",
      isActive: true,
      departmentId: "dept_004",
      departmentName: "Human Resources",
      targetOperator: ">=",
      dataSourceModule: "HR",
      dataSourceField: "RetentionRate",
      trackingFrequency: "Quarterly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Marketing KPIs
    {
      id: "kpi_011",
      name: "Marketing ROI",
      description: "Return on investment for marketing campaigns",
      type: "Percentage",
      category: "marketing",
      targetValue: 300,
      currentValue: 250,
      unit: "%",
      isActive: true,
      departmentId: "dept_005",
      departmentName: "Marketing",
      targetOperator: ">=",
      dataSourceModule: "Marketing",
      dataSourceField: "ROI",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "kpi_012",
      name: "Lead Generation Rate",
      description: "Number of qualified leads generated per month",
      type: "Count",
      category: "marketing",
      targetValue: 200,
      currentValue: 165,
      unit: "leads",
      isActive: true,
      departmentId: "dept_005",
      departmentName: "Marketing",
      targetOperator: ">=",
      dataSourceModule: "Marketing",
      dataSourceField: "LeadGeneration",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  goals: [
    // Company Goals
    {
      id: "goal_001",
      title: "Achieve $5M Fund I AUM by Q4",
      description: "Grow Fund I Assets Under Management to $5,000,000 by end of Q4 2024",
      type: "company",
      category: "financial",
      targetValue: 5000000,
      currentValue: 2500000,
      targetUnit: "USD",
      progressPercentage: 50,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "BalanceSheet.TotalAssets",
      trackingFrequency: "Monthly",
      nextCheckDate: "2024-02-01",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_002",
      title: "Increase Revenue by 25% YoY",
      description: "Achieve 25% year-over-year revenue growth across all business units",
      type: "company",
      category: "financial",
      targetValue: 25,
      currentValue: 18,
      targetUnit: "%",
      progressPercentage: 72,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "IncomeStatement.Revenue",
      trackingFrequency: "Quarterly",
      nextCheckDate: "2024-04-01",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_003",
      title: "Achieve 90% Employee Satisfaction",
      description: "Maintain employee satisfaction score above 90% throughout the year",
      type: "company",
      category: "hr",
      targetValue: 90,
      currentValue: 82,
      targetUnit: "%",
      progressPercentage: 91,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      targetOperator: ">=",
      dataSourceModule: "HR",
      dataSourceField: "SatisfactionScore",
      trackingFrequency: "Quarterly",
      nextCheckDate: "2024-04-01",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Department Goals - Finance
    {
      id: "goal_101",
      title: "Finance: Achieve $2M AUM Growth",
      description: "Finance department responsible for $2M of the $5M AUM target",
      type: "department",
      category: "financial",
      targetValue: 2000000,
      currentValue: 800000,
      targetUnit: "USD",
      progressPercentage: 40,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_001",
      departmentName: "Finance",
      parentGoalId: "goal_001",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "BalanceSheet.TotalAssets",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_102",
      title: "Finance: Maintain 30% Operating Margin",
      description: "Keep operating margin at or above 30% throughout the year",
      type: "department",
      category: "financial",
      targetValue: 30,
      currentValue: 28,
      targetUnit: "%",
      progressPercentage: 93,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_001",
      departmentName: "Finance",
      parentGoalId: "goal_002",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "IncomeStatement.OperatingMargin",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Department Goals - Sales
    {
      id: "goal_201",
      title: "Sales: Acquire 50 New Clients",
      description: "Sales department to acquire 50 new clients contributing to AUM growth",
      type: "department",
      category: "sales",
      targetValue: 50,
      currentValue: 32,
      targetUnit: "clients",
      progressPercentage: 64,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_002",
      departmentName: "Sales",
      parentGoalId: "goal_001",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "ClientAcquisitionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_202",
      title: "Sales: Achieve 35% Conversion Rate",
      description: "Improve lead-to-client conversion rate to 35%",
      type: "department",
      category: "sales",
      targetValue: 35,
      currentValue: 28,
      targetUnit: "%",
      progressPercentage: 80,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_002",
      departmentName: "Sales",
      parentGoalId: "goal_002",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "ConversionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Department Goals - Operations
    {
      id: "goal_301",
      title: "Operations: Achieve 90% Task Completion Rate",
      description: "Maintain 90% on-time task completion rate",
      type: "department",
      category: "operations",
      targetValue: 90,
      currentValue: 85,
      targetUnit: "%",
      progressPercentage: 94,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_003",
      departmentName: "Operations",
      parentGoalId: "goal_002",
      targetOperator: ">=",
      dataSourceModule: "TaskManagement",
      dataSourceField: "TaskCompletionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_302",
      title: "Operations: Improve Process Efficiency to 85%",
      description: "Increase operational efficiency score to 85%",
      type: "department",
      category: "operations",
      targetValue: 85,
      currentValue: 78,
      targetUnit: "%",
      progressPercentage: 92,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_003",
      departmentName: "Operations",
      parentGoalId: "goal_002",
      targetOperator: ">=",
      dataSourceModule: "Operations",
      dataSourceField: "EfficiencyScore",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Department Goals - HR
    {
      id: "goal_401",
      title: "HR: Maintain 95% Employee Retention",
      description: "Keep employee retention rate at or above 95%",
      type: "department",
      category: "hr",
      targetValue: 95,
      currentValue: 92,
      targetUnit: "%",
      progressPercentage: 97,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_004",
      departmentName: "Human Resources",
      parentGoalId: "goal_003",
      targetOperator: ">=",
      dataSourceModule: "HR",
      dataSourceField: "RetentionRate",
      trackingFrequency: "Quarterly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Department Goals - Marketing
    {
      id: "goal_501",
      title: "Marketing: Generate 200 Qualified Leads/Month",
      description: "Generate 200 qualified leads per month to support sales goals",
      type: "department",
      category: "marketing",
      targetValue: 200,
      currentValue: 165,
      targetUnit: "leads",
      progressPercentage: 83,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_005",
      departmentName: "Marketing",
      parentGoalId: "goal_002",
      targetOperator: ">=",
      dataSourceModule: "Marketing",
      dataSourceField: "LeadGeneration",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Individual Goals - Finance Team
    {
      id: "goal_1001",
      title: "John Doe: Process $800K in AUM Transactions",
      description: "Finance Manager responsible for processing $800K in AUM transactions",
      type: "individual",
      category: "financial",
      targetValue: 800000,
      currentValue: 500000,
      targetUnit: "USD",
      progressPercentage: 63,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_001",
      departmentName: "Finance",
      assignedUserId: "user_001",
      assignedUserName: "John Doe",
      parentGoalId: "goal_101",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "BalanceSheet.TotalAssets",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_1002",
      title: "Sarah Johnson: Reduce Operating Costs by 5%",
      description: "Financial Analyst to identify and implement 5% cost reduction",
      type: "individual",
      category: "financial",
      targetValue: 5,
      currentValue: 3,
      targetUnit: "%",
      progressPercentage: 60,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_001",
      departmentName: "Finance",
      assignedUserId: "user_002",
      assignedUserName: "Sarah Johnson",
      parentGoalId: "goal_102",
      targetOperator: ">=",
      dataSourceModule: "Accounting",
      dataSourceField: "IncomeStatement.OperatingExpenses",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Individual Goals - Sales Team
    {
      id: "goal_2001",
      title: "Mike Chen: Acquire 20 New Clients",
      description: "Sales Manager to acquire 20 new high-value clients",
      type: "individual",
      category: "sales",
      targetValue: 20,
      currentValue: 14,
      targetUnit: "clients",
      progressPercentage: 70,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_002",
      departmentName: "Sales",
      assignedUserId: "user_003",
      assignedUserName: "Mike Chen",
      parentGoalId: "goal_201",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "ClientAcquisitionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_2002",
      title: "Emily Davis: Achieve 40% Conversion Rate",
      description: "Sales Representative to achieve 40% lead conversion rate",
      type: "individual",
      category: "sales",
      targetValue: 40,
      currentValue: 32,
      targetUnit: "%",
      progressPercentage: 80,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_002",
      departmentName: "Sales",
      assignedUserId: "user_004",
      assignedUserName: "Emily Davis",
      parentGoalId: "goal_202",
      targetOperator: ">=",
      dataSourceModule: "CRM",
      dataSourceField: "ConversionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Individual Goals - Operations Team
    {
      id: "goal_3001",
      title: "David Wilson: Complete 95% of Tasks On-Time",
      description: "Operations Manager to maintain 95% on-time task completion",
      type: "individual",
      category: "operations",
      targetValue: 95,
      currentValue: 88,
      targetUnit: "%",
      progressPercentage: 93,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_003",
      departmentName: "Operations",
      assignedUserId: "user_005",
      assignedUserName: "David Wilson",
      parentGoalId: "goal_301",
      targetOperator: ">=",
      dataSourceModule: "TaskManagement",
      dataSourceField: "TaskCompletionRate",
      trackingFrequency: "Weekly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "goal_3002",
      title: "Lisa Anderson: Streamline 3 Key Processes",
      description: "Process Improvement Specialist to optimize 3 critical workflows",
      type: "individual",
      category: "operations",
      targetValue: 3,
      currentValue: 2,
      targetUnit: "processes",
      progressPercentage: 67,
      status: "active",
      stage: "execution",
      priority: "medium",
      startDate: "2024-01-01",
      endDate: "2024-06-30",
      departmentId: "dept_003",
      departmentName: "Operations",
      assignedUserId: "user_006",
      assignedUserName: "Lisa Anderson",
      parentGoalId: "goal_302",
      targetOperator: ">=",
      dataSourceModule: "Operations",
      dataSourceField: "ProcessImprovements",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Individual Goals - Marketing Team
    {
      id: "goal_5001",
      title: "Alex Martinez: Generate 80 Leads/Month",
      description: "Marketing Specialist to generate 80 qualified leads per month",
      type: "individual",
      category: "marketing",
      targetValue: 80,
      currentValue: 68,
      targetUnit: "leads",
      progressPercentage: 85,
      status: "active",
      stage: "execution",
      priority: "high",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      departmentId: "dept_005",
      departmentName: "Marketing",
      assignedUserId: "user_007",
      assignedUserName: "Alex Martinez",
      parentGoalId: "goal_501",
      targetOperator: ">=",
      dataSourceModule: "Marketing",
      dataSourceField: "LeadGeneration",
      trackingFrequency: "Monthly",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  tasks: [
    // Tasks for John Doe (Finance Manager)
    {
      id: "task_001",
      title: "Process AUM Transaction Batch 1 - Q1",
      description: "Process first batch of $200K AUM transactions for Q1",
      assignedUserId: "user_001",
      assignedUserName: "John Doe",
      goalId: "goal_1001",
      isPerformanceTask: true,
      status: "completed",
      priority: "high",
      progress: 100,
      dueDate: "2024-01-31",
      completedAt: "2024-01-30T16:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_002",
      title: "Process AUM Transaction Batch 2 - Q1",
      description: "Process second batch of $200K AUM transactions for Q1",
      assignedUserId: "user_001",
      assignedUserName: "John Doe",
      goalId: "goal_1001",
      isPerformanceTask: true,
      status: "completed",
      priority: "high",
      progress: 100,
      dueDate: "2024-02-28",
      completedAt: "2024-02-27T14:30:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_003",
      title: "Process AUM Transaction Batch 3 - Q2",
      description: "Process third batch of $100K AUM transactions for Q2",
      assignedUserId: "user_001",
      assignedUserName: "John Doe",
      goalId: "goal_1001",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "high",
      progress: 50,
      dueDate: "2024-03-31",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_004",
      title: "Process AUM Transaction Batch 4 - Q2",
      description: "Process fourth batch of $300K AUM transactions for Q2",
      assignedUserId: "user_001",
      assignedUserName: "John Doe",
      goalId: "goal_1001",
      isPerformanceTask: true,
      status: "pending",
      priority: "high",
      progress: 0,
      dueDate: "2024-04-30",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Tasks for Sarah Johnson (Financial Analyst)
    {
      id: "task_005",
      title: "Analyze Operating Expenses - Q1",
      description: "Conduct detailed analysis of Q1 operating expenses",
      assignedUserId: "user_002",
      assignedUserName: "Sarah Johnson",
      goalId: "goal_1002",
      isPerformanceTask: true,
      status: "completed",
      priority: "medium",
      progress: 100,
      dueDate: "2024-02-15",
      completedAt: "2024-02-14T10:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_006",
      title: "Implement Cost Reduction Initiative 1",
      description: "Implement first cost reduction initiative targeting 2% savings",
      assignedUserId: "user_002",
      assignedUserName: "Sarah Johnson",
      goalId: "goal_1002",
      isPerformanceTask: true,
      status: "completed",
      priority: "medium",
      progress: 100,
      dueDate: "2024-03-15",
      completedAt: "2024-03-14T15:30:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_007",
      title: "Implement Cost Reduction Initiative 2",
      description: "Implement second cost reduction initiative targeting 1% savings",
      assignedUserId: "user_002",
      assignedUserName: "Sarah Johnson",
      goalId: "goal_1002",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "medium",
      progress: 60,
      dueDate: "2024-04-30",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Tasks for Mike Chen (Sales Manager)
    {
      id: "task_008",
      title: "Close Deal with Acme Corp",
      description: "Finalize contract negotiations with Acme Corp ($500K AUM)",
      assignedUserId: "user_003",
      assignedUserName: "Mike Chen",
      goalId: "goal_2001",
      isPerformanceTask: true,
      status: "completed",
      priority: "high",
      progress: 100,
      dueDate: "2024-01-20",
      completedAt: "2024-01-19T17:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_009",
      title: "Onboard 5 New Clients - Q1",
      description: "Complete onboarding process for 5 new clients acquired in Q1",
      assignedUserId: "user_003",
      assignedUserName: "Mike Chen",
      goalId: "goal_2001",
      isPerformanceTask: true,
      status: "completed",
      priority: "high",
      progress: 100,
      dueDate: "2024-02-28",
      completedAt: "2024-02-26T12:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_010",
      title: "Acquire 8 New Clients - Q2",
      description: "Acquire 8 new high-value clients in Q2",
      assignedUserId: "user_003",
      assignedUserName: "Mike Chen",
      goalId: "goal_2001",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "high",
      progress: 38,
      dueDate: "2024-06-30",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Tasks for Emily Davis (Sales Representative)
    {
      id: "task_011",
      title: "Follow Up with 50 Warm Leads",
      description: "Follow up with 50 warm leads from marketing campaigns",
      assignedUserId: "user_004",
      assignedUserName: "Emily Davis",
      goalId: "goal_2002",
      isPerformanceTask: true,
      status: "completed",
      priority: "high",
      progress: 100,
      dueDate: "2024-02-15",
      completedAt: "2024-02-14T16:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_012",
      title: "Conduct 30 Product Demos",
      description: "Conduct 30 product demonstrations for qualified prospects",
      assignedUserId: "user_004",
      assignedUserName: "Emily Davis",
      goalId: "goal_2002",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "high",
      progress: 70,
      dueDate: "2024-03-31",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Tasks for David Wilson (Operations Manager)
    {
      id: "task_013",
      title: "Complete Q1 Operational Tasks",
      description: "Complete all assigned operational tasks for Q1 on time",
      assignedUserId: "user_005",
      assignedUserName: "David Wilson",
      goalId: "goal_3001",
      isPerformanceTask: true,
      status: "completed",
      priority: "medium",
      progress: 100,
      dueDate: "2024-03-31",
      completedAt: "2024-03-30T18:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_014",
      title: "Optimize Team Task Allocation",
      description: "Review and optimize task allocation across operations team",
      assignedUserId: "user_005",
      assignedUserName: "David Wilson",
      goalId: "goal_3001",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "medium",
      progress: 45,
      dueDate: "2024-04-15",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Tasks for Lisa Anderson (Process Improvement Specialist)
    {
      id: "task_015",
      title: "Streamline Invoice Processing Workflow",
      description: "Analyze and optimize the invoice processing workflow",
      assignedUserId: "user_006",
      assignedUserName: "Lisa Anderson",
      goalId: "goal_3002",
      isPerformanceTask: true,
      status: "completed",
      priority: "medium",
      progress: 100,
      dueDate: "2024-02-28",
      completedAt: "2024-02-27T14:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_016",
      title: "Optimize Client Onboarding Process",
      description: "Redesign and streamline the client onboarding process",
      assignedUserId: "user_006",
      assignedUserName: "Lisa Anderson",
      goalId: "goal_3002",
      isPerformanceTask: true,
      status: "completed",
      priority: "medium",
      progress: 100,
      dueDate: "2024-04-15",
      completedAt: "2024-04-14T11:30:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_017",
      title: "Improve Reporting Workflow",
      description: "Streamline the monthly reporting workflow for efficiency",
      assignedUserId: "user_006",
      assignedUserName: "Lisa Anderson",
      goalId: "goal_3002",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "medium",
      progress: 55,
      dueDate: "2024-06-30",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Tasks for Alex Martinez (Marketing Specialist)
    {
      id: "task_018",
      title: "Launch Q1 Marketing Campaign",
      description: "Execute Q1 digital marketing campaign targeting 30 leads",
      assignedUserId: "user_007",
      assignedUserName: "Alex Martinez",
      goalId: "goal_5001",
      isPerformanceTask: true,
      status: "completed",
      priority: "high",
      progress: 100,
      dueDate: "2024-02-28",
      completedAt: "2024-02-27T16:00:00.000Z",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_019",
      title: "Optimize SEO Strategy",
      description: "Implement SEO improvements to generate 20 organic leads/month",
      assignedUserId: "user_007",
      assignedUserName: "Alex Martinez",
      goalId: "goal_5001",
      isPerformanceTask: true,
      status: "in_progress",
      priority: "high",
      progress: 65,
      dueDate: "2024-04-30",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "task_020",
      title: "Create Content Marketing Strategy",
      description: "Develop content marketing strategy to generate 30 leads/month",
      assignedUserId: "user_007",
      assignedUserName: "Alex Martinez",
      goalId: "goal_5001",
      isPerformanceTask: true,
      status: "pending",
      priority: "medium",
      progress: 0,
      dueDate: "2024-05-31",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  departments: [
    {
      id: "dept_001",
      name: "Finance",
      description: "Financial operations and management",
      branch: "main_office",
      isActive: true,
      _count: { users: 12, goals: 4 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dept_002",
      name: "Sales",
      description: "Sales and business development",
      branch: "main_office",
      isActive: true,
      _count: { users: 8, goals: 4 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dept_003",
      name: "Operations",
      description: "Operational efficiency and support",
      branch: "main_office",
      isActive: true,
      _count: { users: 15, goals: 4 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dept_004",
      name: "Human Resources",
      description: "Employee management and development",
      branch: "main_office",
      isActive: true,
      _count: { users: 5, goals: 2 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dept_005",
      name: "Marketing",
      description: "Marketing and brand management",
      branch: "main_office",
      isActive: true,
      _count: { users: 6, goals: 3 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  departmentScorecards: [
    {
      departmentId: "dept_001",
      departmentName: "Finance",
      totalGoals: 4,
      completedGoals: 0,
      inProgressGoals: 4,
      overdueGoals: 0,
      averageProgress: 52,
      performanceRating: "Good",
      goals: [],
      teamMembers: [
        {
          userId: "user_001",
          name: "John Doe",
          totalTasks: 4,
          completedTasks: 2,
          inProgressTasks: 1,
          performanceRating: "Good",
        },
        {
          userId: "user_002",
          name: "Sarah Johnson",
          totalTasks: 3,
          completedTasks: 2,
          inProgressTasks: 1,
          performanceRating: "Good",
        },
      ],
    },
    {
      departmentId: "dept_002",
      departmentName: "Sales",
      totalGoals: 4,
      completedGoals: 0,
      inProgressGoals: 4,
      overdueGoals: 0,
      averageProgress: 74,
      performanceRating: "Good",
      goals: [],
      teamMembers: [
        {
          userId: "user_003",
          name: "Mike Chen",
          totalTasks: 3,
          completedTasks: 2,
          inProgressTasks: 1,
          performanceRating: "Excellent",
        },
        {
          userId: "user_004",
          name: "Emily Davis",
          totalTasks: 2,
          completedTasks: 1,
          inProgressTasks: 1,
          performanceRating: "Good",
        },
      ],
    },
    {
      departmentId: "dept_003",
      departmentName: "Operations",
      totalGoals: 4,
      completedGoals: 0,
      inProgressGoals: 4,
      overdueGoals: 0,
      averageProgress: 84,
      performanceRating: "Excellent",
      goals: [],
      teamMembers: [
        {
          userId: "user_005",
          name: "David Wilson",
          totalTasks: 2,
          completedTasks: 1,
          inProgressTasks: 1,
          performanceRating: "Excellent",
        },
        {
          userId: "user_006",
          name: "Lisa Anderson",
          totalTasks: 3,
          completedTasks: 2,
          inProgressTasks: 1,
          performanceRating: "Excellent",
        },
      ],
    },
    {
      departmentId: "dept_005",
      departmentName: "Marketing",
      totalGoals: 3,
      completedGoals: 0,
      inProgressGoals: 3,
      overdueGoals: 0,
      averageProgress: 85,
      performanceRating: "Excellent",
      goals: [],
      teamMembers: [
        {
          userId: "user_007",
          name: "Alex Martinez",
          totalTasks: 3,
          completedTasks: 1,
          inProgressTasks: 1,
          performanceRating: "Excellent",
        },
      ],
    },
  ],
  userScorecards: [
    {
      userId: "user_001",
      userName: "John Doe",
      department: "Finance",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 63,
      performanceRating: "Good",
      goals: [],
      tasks: [],
    },
    {
      userId: "user_002",
      userName: "Sarah Johnson",
      department: "Finance",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 60,
      performanceRating: "Good",
      goals: [],
      tasks: [],
    },
    {
      userId: "user_003",
      userName: "Mike Chen",
      department: "Sales",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 70,
      performanceRating: "Excellent",
      goals: [],
      tasks: [],
    },
    {
      userId: "user_004",
      userName: "Emily Davis",
      department: "Sales",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 80,
      performanceRating: "Good",
      goals: [],
      tasks: [],
    },
    {
      userId: "user_005",
      userName: "David Wilson",
      department: "Operations",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 93,
      performanceRating: "Excellent",
      goals: [],
      tasks: [],
    },
    {
      userId: "user_006",
      userName: "Lisa Anderson",
      department: "Operations",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 67,
      performanceRating: "Excellent",
      goals: [],
      tasks: [],
    },
    {
      userId: "user_007",
      userName: "Alex Martinez",
      department: "Marketing",
      totalGoals: 1,
      completedGoals: 0,
      inProgressGoals: 1,
      overdueGoals: 0,
      averageProgress: 85,
      performanceRating: "Excellent",
      goals: [],
      tasks: [],
    },
  ],
  loading: false,
  crudLoading: false,
  error: null,
  selectedKPIType: "all",
  selectedKPICategory: "all",
  selectedKPIDepartment: "all",
  selectedKPIStatus: "all",
  kpiSearchTerm: "",
  metrics: {
    totalKPIs: 12,
    activeKPIs: 12,
    completedGoals: 0,
    totalGoals: 18,
    completedTasks: 10,
    totalTasks: 20,
  },
}

const performanceSlice = createSlice({
  name: "performance",
  initialState,
  reducers: {
    setDepartmentScorecards: (state, action: PayloadAction<DepartmentScorecard[]>) => {
      state.departmentScorecards = action.payload
    },
    setUserScorecards: (state, action: PayloadAction<UserScorecard[]>) => {
      state.userScorecards = action.payload
    },
  },
})

export const { setDepartmentScorecards, setUserScorecards } = performanceSlice.actions

export default performanceSlice.reducer
